version: 'alpha'

services:
  db:
    container_name: db
    hostname: db
    image: mysql:latest
    environment:
      MYSQL_USER: thibault_test
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 8889:3306
    volumes:
      - ./database/fromagerie_com_springBoot.sql:/docker-entrypoint-initdb.d/fromagerie_com_springBoot.sql
      - data:/var/lib/mysql

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer:latest
    ports:
      - 8890:8080

volumes:
  data:

networks:
  default:
    name: fromagerie
